swagger: '2.0'
info:
  version: 0.0.1
  title: Notifications service API
  description: |
    Notifications API is used for getting notifications and marking them as read
schemes:
- http
basePath: /api/v1
consumes:
- application/json
produces:
- application/json
paths:
  /notifications:
    get:
      summary: Get a list of Notifications
      description: >
        This API delivers the Notifications in a structured collection.
      tags:
      - Notification
      parameters:
      - name: category
        in: query
        description: notification category
        type: string
        required: false
        enum:
        - DEBUG
        - INFO
        - ERROR
        - CRIT
        - WARN
      - name: isRead
        in: query
        description: in case when isRead not set - read and not read notifications will be returned
        type: boolean
        enum:
        - true
        - false
        required: false
      - name: page
        in: query
        description: page number
        type: integer
        required: true
      - name: perPage
        in: query
        description: results per page
        type: integer
        required: true
      security:
      - x_auth: []
      responses:
        '200':
          description: successful request
        '405':
          description: Not allowed - Method is not allowed on the current resource
        '500':
          description: Internal Error - Internal server error
        default:
          description: Unexpected error
    put:
      summary: mark all as read
      description: |
        This service marks all Notifications as read.
      tags:
      - Notification
      security:
      - x_auth: []
      responses:
        '200':
          description: successful request
        '405':
          description: Not allowed - Method is not allowed on the current resource
        '500':
          description: Internal Error - Internal server error
        default:
          description: Unexpected error
  '/notifications/{id}':
    put:
      summary: Mark single notification as read
      description: |
        The Notification with the given ID will be marked as read.
      parameters:
      - name: id
        in: path
        description: id of notification item
        required: true
        type: string
      tags:
      - Notification
      security:
      - x_auth: []
      responses:
        '200':
          description: successful request
        '405':
          description: Not allowed - Method is not allowed on the current resource
        '500':
          description: Internal Error - Internal server error
        default:
          description: Unexpected error
definitions:
  Notification:
    type: object
    properties:
      ID:
        type: string
      createdOn:
        type: string
      isRead:
        type: boolean
      readOn:
        type: string
      text:
        type: string
      category:
        type: string
        enum:
        - DEBUG
        - INFO
        - ERROR
        - CRIT
        - WARN
      priority:
        type: string
        enum:
        - VERYLOW
        - LOW
        - NORMAL
        - HIGH
        - URGENT
      isPrivate:
        type: boolean
